name: betterstack

services:
  frontend:
    container_name: bs-frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      target: development
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
      - /usr/src/app/frontend/.next
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.development
    environment:
      NODE_ENV: development
      BACKEND_BASE_URL: "http://backend:3010"
    depends_on:
      - backend

  backend:
    container_name: bs-backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: development
    volumes:
      - ./backend:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
    ports:
      - "3010:3010"
    environment:
      PORT: 3010
      POSTGRES_HOST: postgres
    env_file:
      - ./backend/.env.development
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: bs-postgres
    image: postgres:18-alpine
    volumes:
      - postgres-volume:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: betterstack_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d betterstack_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres-volume:
