name: betterstack

services:
  frontend:
    container_name: bs-frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      target: development
    volumes:
      - ./frontend:/usr/src/app/frontend    # for hot-reload
      - /usr/src/app/frontend/node_modules  # but prevent overwriting container's node_modules
      - /usr/src/app/frontend/.next         # as well as .next
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      BACKEND_BASE_URL: "http://backend:3010"
    depends_on:
      - backend

  backend:
    container_name: bs-backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: development
    volumes:
      - ./backend:/usr/src/app/backend      # for hot-reload
      - /usr/src/app/backend/node_modules   # but prevent overwriting container's node_modules
    ports:
      - "3010:3010"
    environment:
      POSTGRES_HOST: postgres
    env_file:
      - ./backend/.env.development
    depends_on:
      - postgres

  postgres:
    container_name: bs-postgres
    image: postgres:18
    volumes:
      - postgres-volume:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: betterstack_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "betterstack_db"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  postgres-volume:
